config/routes.rb
Rails.application.routes.draw do


  resources :labels, only: [:show]

  resources :topics do
    resources :posts, except: [:index]
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  resources :users, only: [:show, :new, :create]
  resources :sessions, only: [:new, :create, :destroy]

  get 'about' => 'welcome#about'
  root 'welcome#index'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show, :create, :update]
      resources :topics, only: [:index, :show, :update, :create, :destroy]
      resources :posts, only: [:index, :show, :update, :create, :destroy]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :require_sign_in

  def create
    post = Post.find(params[:post_id])
    favorite = post.favorites.new(user: current_user)

    if favorite.save
      flash[:notice] = "Post favrited"
    else
      flash[:error] = "Favoriting failed."
    end
    redirect_to [post.topic, post] # post show page
  end

  def destroy
    post = Post.find(params[:post_id])
    favorite = post.favorites.find(params[:id])
    if favorite.destroy
      flash[:notice] = "You Unfavorited this post."
    #  redirect_to [post.topic, post] # post show page
    else
      flash[:error] = "There was an error favoriting this post. Please try again."
    #  redirect_to [post.topic, post] # post show page
    end
    redirect_to [post.topic, post]
  end


end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if favorite = current_user.favorite_for(post) %>
  <%#= link_to "Unfavorite", post_favorite_path(post, favorite), method: :delete, class: "btn btn-danger glyphicon glyphicon-star-empty" %>
  <%= link_to [post, favorite], method: :delete, class: "btn btn-danger" do %>
    <i class="glyphicon glyphicon-star-empty"></i> &nbsp; Unfavorite
  <% end %>

<% else %>
  <%#= link_to post_favorites_path(post), class: 'btn btn-primary', method: :post do %><!-- this is also OK -->
  <%= link_to [post, Favorite.new], class: 'btn btn-primary', method: :post do %>
    <i class="glyphicon glyphicon-star"></i> &nbsp; Favorite
  <% end %>

<% end %>