config/routes.rb
Rails.application.routes.draw do


  resources :labels, only: [:show]

  resources :topics do
    resources :posts, except: [:index]
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  resources :users, only: [:show, :new, :create]
  resources :sessions, only: [:new, :create, :destroy]

  get 'about' => 'welcome#about'
  root 'welcome#index'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show, :create, :update]
      resources :topics, only: [:index, :show, :update, :create, :destroy]
      resources :posts, only: [:index, :show, :update, :create, :destroy]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :posts, dependent: :destroy

  # define a has_many relationship between Topic and Labeling, using the  labeleable interface
  has_many :labelings, as: :labelable

  # define a has_many relationship between Topic to Label,
  # using the  Labeling class through the labeleable interface.
  has_many :labels, through: :labelings

  scope :publicly_viewable, -> { self.where(public: true) }
  scope :privately_viewable, -> { self.where(public: false) }
  #scope :visible_to, -> (user) { user ? all : where(public: true ) }
  scope :visible_to, -> (user) { user ? all : publicly_viewable }

end

app/controllers/api/v1/topics_controller.rb
class Api::V1::TopicsController < Api::V1::BaseController
  before_action :authenticate_user, except: [:index, :show]
  before_action :authorize_user, except: [:index, :show]

  def index
    topics = Topic.all
    render json: topics, status: 200
  end

  def show
    topic = Topic.find(params[:id])
    render json: topic, status: 200
  end

  def update
    topic = Topic.find(params[:id])
    if topic.update_attributes(topic_params)
      render json: topic, status: 200
    else
      render json: { error: "Topic update failed", status: 400 }, status: 400
    end
  end

  def create
    topic = Topic.new(topic_params)
    if topic.valid?
      topic.save
      render json: topic, status: 200
    else
      render json: { error: "Topic is invalid", status: 400 }, status: 400
    end
  end

  def destroy
    topic = Topic.find(params[:id])
    if topic.destroy
      render json: { message: "Topic destroyed", status: 200 }, status: 200
      # response.body = { message: "Topic destroyed", status: 200 }   .to_json
    else
      render json: { error: "Error deleting topic", status: 400 }, status: 400
    end
  end

  private
  def topic_params
    params.require(:topic).permit(:name, :description)
  end

end

app/controllers/topics/comments_controller.rb
class Topics::CommentsController < CommentsController
  before_action :set_commentable # 3rd
  #before_action :authorize_user, only: [:destroy]

  private
  def set_commentable
    @commentable = Topic.find(params[:topic_id])
  end

  # def authorize_user
  #   #@post = Post.find(params[:post_id])
  #   @comment = @commentable.comments.find(params[:id])
  # #  raise
  #   unless current_user == @comment.user || current_user.admin?
  #     flash[:alert] = "You do not have permission to delete a comment."
  #     redirect_to [@commentable.topic, @commentable] # post show
  #     #redirect_to [@post.topic, @post] # post show page
  #   end
  # end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  #include LabelsHelper
  before_action :require_sign_in, except: [:index, :show]
  before_action :authorize_user, except: [:index, :show]

  def index
    #@topics = Topic.all
    @topics = Topic.all.visible_to(current_user)
  end

  def show
    @topic = Topic.find(params[:id])
    unless @topic.public || current_user
      flash[:alert] = "You must be signed in to view private topics."
      redirect_to new_session_path
    end
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      @topic.labels = Label.update_labels(params[:topic][:labels])
      flash[:notice] = "The topic was saved successfully!"
      redirect_to @topic
    else
      flash[:error] = "Error creating topic. Please try again."
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
  #  byebug
    @topic.assign_attributes(topic_params)
    if @topic.save
#    if @topic.update_attributes(topic_params) ## this is equivalent to assign_attributes then save
#    but .update_attributes is not equivalent to assign_attributes by themselves
      @topic.labels = Label.update_labels(params[:topic][:labels])
      # after @topic is saved create the label
      flash[:notice] = "The topic was udated successfully!"
      redirect_to @topic
    else
      flash[:error] = "Error updating the topic. Please try again."
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    if @topic.destroy
      flash[:notice] = "The topic was deleted!"
      redirect_to topics_url
    end
  end

  private
  def topic_params
    params.require(:topic).permit(:name, :public, :description)
  end

  def authorize_user
    unless current_user.admin?
      flash[:alert] = "You must be an admin to do that."
      redirect_to topics_path
    end
  end

end

app/helpers/topics_helper.rb
module TopicsHelper

  def user_is_authorized_for_topics?
    current_user && current_user.admin?
  end

  def user_is_authorized_for_topic_edit?
    current_user && (current_user.admin? || current_user.moderator?)
  end

end

app/views/topics/_form.html.erb
<%= form_for topic do |f| %>

  <% if topic.errors.any? %>
    <h4><%= pluralize topic.errors.count, "error" %></h4>
      <% topic.errors.full_messages.each do |msg| %>
        <ul>
          <li><%= msg %></li>
        </ul>
      <% end %>
  <% end %>

  <%= form_tag_group(topic.errors[:name]) do %>
  <%#= topic.errors[:name] %>
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", placeholder: "Enter topic name", autofocus: true %>
  <% end %>

  <%= form_tag_group(topic.errors[:description]) do %>
    <%= f.label :description %>
    <%= f.text_area :description, rows: 8, class: "form-control", placeholder: "Enter topic description" %>
  <% end %>

  <div class="form-group">
    <%= f.submit "Save", class: "btn btn-success" %>
  </div>

<% end %>

app/views/topics/_topic.html.erb
<div class="media">
  <div class="media-body">
    <h4 class="media-heading">
      <%= link_to topic.name, topic_path(topic) %>
    </h4>
    <small>
      <%= topic.description %>
    </small>
  </div>
</div>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>

  <div class="row">
    <div class="col-sm-4">
      <p>Guidelines for topics</p>
      <ul>
        <li>Make sure it rhymes.</li>
        <li>Don't use the letter A</li>
        <li>The incessant use of hashtags will get you banned.</li>
      </ul>
    </div>

    <div class="col-sm-8">

      <%= form_for @topic do |f| %>

        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control", placeholder: "Enter topic name", autofocus: true %>
        </div>

        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, rows: 8, class: "form-control", placeholder: "Enter topic description" %>
        </div>

        <div class="form-group">
          <%= render partial: 'labels/form', locals: { f: f, labels: @topic.labels } %>
        </div>

        <div class="form-group">
          <%= f.submit "Save", class: "btn btn-success" %>
        </div>

      <% end %>

    </div>
  </div>

app/views/topics/index.html.erb
<h1>All Topics</h1>

<div class="row">
  <div class="col-md-8">

    <%#= render @topics %>

    <% @topics.each do |topic| %>
      <%= render partial: 'topic', locals: { topic: topic } %>
    <% end %>

    <!-- moved to partial _topic.html.erb

      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%#= link_to topic.name, topic_path(topic) %>
          </h4>
          <small>
            <%#= topic.description %>
          </small>
        </div>
      </div>
     -->

  </div>

    <%# if current_user && current_user.admin? %>
    <% if user_is_authorized_for_topics? %>
      <div class="col-md-4">
        <%= link_to "New Topic", new_topic_path, class: "btn btn-success" %>
      </div>
    <% end %>

</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>

  <div class="row">
    <div class="col-sm-4">
      <p>Guidelines for topics</p>
      <ul>
        <li>Make sure it rhymes.</li>
        <li>Don't use the letter A</li>
        <li>The incessant use of hashtags will get you banned.</li>
      </ul>
    </div>


    <div class="col-sm-8">

      <%= form_for @topic do |f| %>

        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control", placeholder: "Enter topic name", autofocus: true %>
        </div>

        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, rows: 8, class: "form-control", placeholder: "Enter topic description" %>
        </div>

        <div class="form-group">
          <%= render partial: 'labels/form', locals: { f: f , labels: @topic.labels }  %>
        </div>

        <div class="form-group">
          <%= f.submit "Save", class: "btn btn-success" %>
        </div>

      <% end %>

    </div>
  </div>

app/views/topics/show.html.erb
<h1><%= @topic.name %></h1>

<% if user_is_authorized_for_topics? %>
  <%= link_to "Edit Topic", edit_topic_path(@topic), class: "btn btn-success" %>
  <%= link_to "Delete Topic", topic_path(@topic), method: :delete, data: {confirm: 'Are you sure you want to delete this topic?'}, class: "btn btn-danger" %>
<% end %>

<div class="row">
  <div class="col-md-8">
    <p class="lead">
      <%= render partial: 'labels/list', locals: { labels: @topic.labels }  %><br>
      <%=@topic.description %></p>

      <hr>

        <%= render partial: 'comments/comment', locals: { commentable: @topic } %>

        <%= render partial: 'comments/form', locals: { commentable: @topic } if current_user %>

      <hr>

    <% if @topic.posts.any? %>
      <h4>Posts for this topic: </h4>

      <% @topic.posts.each do |post| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%#= link_to(post.title, [post.topic, post]) %>
            <%= link_to post.title, topic_post_path(@topic, post) %>
            <%= render partial: 'labels/list', locals: { labels: post.labels }  %>
          </h4>
          <small>
            submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %><br>
            <%= post.comments.count %> Comments
          </small>
        </div>
      </div>
      <% end %>

    <% else %>
      <h4>No post for this topic:</h4>
    <% end %>


  </div>

  <% if current_user %>
    <div class="col-md-4">
      <%#= link_to "New Post", new_topic_post_path(@topic), class: "btn btn-success" %>
      <%= link_to "New Post", new_topic_post_path(@topic), class: "btn btn-success" %>
    </div>
  <% end %>


</div>