config/routes.rb
Rails.application.routes.draw do


  resources :labels, only: [:show]

  resources :topics do
    resources :posts, except: [:index]
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  resources :users, only: [:show, :new, :create]
  resources :sessions, only: [:new, :create, :destroy]

  get 'about' => 'welcome#about'
  root 'welcome#index'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show, :create, :update]
      resources :topics, only: [:index, :show, :update, :create, :destroy]
      resources :posts, only: [:index, :show, :update, :create, :destroy]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic#, optional: true # posts needs topic bypass for now
  belongs_to :user#, optional: true
  has_many :comments, dependent: :destroy

  has_many :labelings, as: :labelable
  has_many :labels, through: :labelings

  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :topic, presence: true
  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true, length: { minimum: 20 }

  # added per bloc but rails 5 automatically sets these unless bypassed
  validates :topic, presence: true
  validates :user, presence: true

  #default_scope { order('created_at DESC') }
  default_scope { self.order('rank DESC') }

  scope :visible_to, -> (user) { user ? all : joins(:topic).where('topics.public' => true) }
  # this is using the ternery operator  ? :    or   if "something" then "give this" else "give that"
  # if (there is a) user scope all else    joins(:topic).where('topics.public' => true)
  # self (or Post)    self.joins(:topic)  the ouputs are posts that belongs_to topic  w/ attributes public: true
  # meaning if not signed in you will only get scped the public topic.posts
  # private topics are only for signed users

  def up_votes
    votes.where(value: 1).count
  end

  def down_votes
    votes.where(value: -1).count
  end

  def points
  #  up_votes - down_votes # works
    votes.sum(:value)
  end

  def update_rank
    age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
    new_rank = points + age_in_days
    update_attribute(:rank, new_rank)
  end


end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::V1::BaseController
  before_action :authenticate_user, except: [:index, :show]
  before_action :authorize_user, except: [:index, :show]

  def index
    posts = Post.all
    render json: posts, status: 200
  end

  def show
    post = Post.find(params[:id])
    render json: post, status: 200
  end

  def update
    topic = Topic.find(params[:topic_id])
    post = topic.posts.find(params[:id])
    if post.update_attributes(post_params)
      render json: post, status: 200
    else
      render json: { error: "Update post failed", status: 400 }, status: 400
    end
  end

  def create
    topic = Topic.find(params[:topic_id])
    post = topic.posts.new(post_params)
    post.user = @current_user
    if post.valid?
      post.save!
      render json: post, status: 200
    else
      render json: { error: "Post is invalid", status: 400 }, status: 400
    end
  end

  def destroy
    topic = Topic.find(params[:topic_id])
    post = topic.posts.find(params[:id])
    if post.destroy
      render json: { message: "Post destroyed", status: 200 }, status: 200
    else
    end

  end

  private
  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < CommentsController
  before_action :set_commentable # 3rd
#  before_action :authorize_user, only: [:destroy]

  private
  def set_commentable
    @commentable = Post.find(params[:post_id])
  end

  # def authorize_user
  #   #@post = Post.find(params[:post_id])
  #   @comment = @commentable.comments.find(params[:id])
  # #  raise
  #   unless current_user == @comment.user || current_user.admin?
  #     flash[:alert] = "You do not have permission to delete a comment."
  #     redirect_to [@commentable.topic, @commentable] # post show
  #     #redirect_to [@post.topic, @post] # post show page
  #   end
  # end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_sign_in, except: [:show]
  before_action :authorized_user, except: [:show, :new, :create]

  def show
    #@topic = Topic.find(params[:topic_id])
    #@posts = @topic.posts.find(params[:id])
    @post = Post.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = @topic.posts.new(post_params)
    @post.user = current_user

    if @post.save
      @post.labels = Label.update_labels(params[:post][:labels])
      flash[:notice] = "Your post was saved successfully!"
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      @post.labels = Label.update_labels(params[:post][:labels])
      flash[:notice] = "Post was updated successfully!"
      redirect_to [@post.topic, @post]
    else
      flash[:error] = "There was a problem updating post. Please try again."
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:notice] = "The post was deleted."
      redirect_to(@post.topic)
    else
      flash[:error] = "There was an error deleting the post. Please try again."
      render :show
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :body)
  end

  def authorized_user
    post = Post.find(params[:id])
    unless post.user == current_user || current_user.admin?
      flash[:alert] = "You are not authorized to do this action."
      redirect_to [post.topic, post]
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper

  # original
  # def user_is_authorized_for_post?(post)
  #   current_user && (current_user == post.user || current_user.admin?)
  # end

  def user_is_authorized_for_post_edit?(post)
     current_user && (current_user == post.user || current_user.admin? || current_user.moderator?)
   end

  def user_is_authorized_for_post_delete?(post)
    current_user && (current_user == post.user || current_user.admin?)
  end

end

app/views/posts/_form.html.erb
<%= form_for [topic, post] do |f| %>

    <% if post.errors.any? %>
      <div>
        <h4><%= pluralize post.errors.count, "error" %> occured: </h4>
        <% post.errors.full_messages.each do |msg| %>
          <ul>
            <li><%= msg %></li>
          </ul>
        <% end %>
      </div>
    <% end %>

  <%= form_tag_group(post.errors[:title]) do  %>
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", placeholder: "Enter post title", autofocus: true %>
  <% end %>

  <%= form_tag_group(post.errors[:body]) do  %>
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: "form-control", placeholder: "Enter post body" %>
  <% end %>

  <div class="form-group">
    <%= render partial: 'labels/form', locals: { f: f, labels: @post.labels } %>
  </div>

  <div class="form-group">
    <%= f.submit "Save", class: "btn btn-success" %>
  </div>

<% end %>

app/views/posts/_post.html.erb
<div class="media">
   <%= render partial: 'votes/voting', locals: { post: post } %>
   <div class="media-body">
     <h4 class="media-heading">
       <%= link_to post.title, topic_post_path(post.topic, post) %>
       <%= render partial: "labels/list", locals: { labels: post.labels } %>
     </h4>
     <small>
       submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %>
       <%= image_tag(post.user.avatar_url(25), class: "gravatar") %><br>
       <%= post.comments.count %> Comments
     </small>
   </div>
 </div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

  <div class="row">
    <div class="col-sm-4">
      <p>Guidelines for posts</p>
      <ul>
        <li>Make sure it rhymes.</li>
        <li>Don't use the letter A</li>
        <li>The incessant use of hashtags will get you banned.</li>
      </ul>
    </div>


    <div class="col-sm-8">

      <%#= form_for @post, url:  topic_post_path(@post.topic, @post)  do |f| %><!-- long way -->
      <%= render partial: 'form', locals: { topic: @post.topic, post: @post } %>

    </div>
  </div>

app/views/posts/index.html.erb
<!-- not used anymore; no post index-->
<h1>All Posts</h1>

<div class="row">
  <div class="col-md-8">

    <% @posts.each do |post| %>
    <div class="media">
      <div class="media-body">
        <h4 class="media-heading">
          <%= link_to(post.title, post) %>
        </h4>
      </div>
    </div>
    <% end %>

  </div>

  <div class="col-md-4">
    <%= link_to "New Post", new_post_path, class: "btn btn-success" %>
  </div>

</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

  <div class="row">
    <div class="col-sm-4">
      <p>Guidelines for posts</p>
      <ul>
        <li>Make sure it rhymes.</li>
        <li>Don't use the letter A</li>
        <li>The incessant use of hashtags will get you banned.</li>
      </ul>
    </div>


    <div class="col-sm-8">

      <%= render partial: 'form', locals: { topic: @topic, post: @post } %>

    </div>
  </div>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-md-8">

    <div>

        <%= render partial: 'votes/voting', locals: { post: @post } %>

      <h1>
        <%= @post.title %><br>
        <small>
          submitted <%= time_ago_in_words @post.created_at %> ago by <%= @post.user.name %>
        </small>
      </h1>
    </div>

    <%= @post.body %><br>

  </div>

  <% if user_is_authorized_for_post?(@post) %>

    <div class="col-md-4">
      <%= link_to "Edit Post", edit_topic_post_path(@post.topic, @post), class: "btn btn-success" %>
      <%= link_to "Delete Post", topic_post_path(@post.topic, @post), method: :delete, data: {confirm: 'Are you sure you want to delete this post?'}, class: "btn btn-danger" %><br>
      <%= render partial: 'labels/list', locals: { labels: @post.labels }  %>
    </div>

  <% end %>

  <div class="col-md-4">
    <div class="js-points2">
      <h4><%= pluralize @post.points, "point" %></h4>
    </div>

    <div>
      <small>
        <span class="js-up-vote">
          <%= pluralize @post.up_votes, "up vote" %> |
        </span>
        <span class="js-down-vote">
          <%= pluralize @post.down_votes, "down vote" %>
        </span>
      </small>
    </div>
  </div>

  <% if current_user %>
    <%= render partial: 'favorites/favorite', locals: { post: @post } %>
  <% end %>

  <div class="col-md-8">
    <% if @post.comments.any? %>

      <!-- <div class="js-comments-count2"> -->
      <div class="js-comments-count2">
        <h4><%= pluralize @post.comments.count, "comment" %> for this post: </h4>
      </div>

      <div class="js-comments">
        <%= render @post.comments %>
      </div>

    <% else %>
      <h4>No comment for this post:</h4>
    <% end %>

    <% if current_user %>

      <h4>Add a comment:</h4>

      <div class="new-comment">
        <%= render 'comments/form', comment: Comment.new, post: @post  %>
      </div>

    <% end %>

  </div>

</div>